import type { LaboratoryMethodOption } from "./method-selector";

export type LaboratoryMethodModule = "integral" | "differential" | "matrix" | "probability" | "series-limit";

const active = "active" as const;
const adapter = "adapter" as const;
const planned = "planned" as const;

export const laboratoryMethodRegistry: Record<LaboratoryMethodModule, LaboratoryMethodOption[]> = {
    integral: [
        {
            id: "auto",
            label: "Auto researcher route",
            family: "hybrid",
            engine: "SymPy",
            status: active,
            description: "Ifoda, bound, singularity va closed-form signaliga qarab symbolic-first route tanlaydi.",
            detail: "Hozir backend SymPy integrate lane bilan ishlaydi va decimal confirmationni reproducibility payloadga yozadi.",
            bestFor: ["unknown integral type", "template examples", "symbolic-first workflow"],
            parameters: ["timeout", "precision", "singularity check"],
            limitations: ["independent quadrature hali hamma metodda ulanmagan"],
        },
        {
            id: "symbolic",
            label: "SymPy symbolic integrate",
            family: "analytic",
            engine: "SymPy",
            status: active,
            description: "Closed-form primitive yoki definite exact value topishni ustuvor qiladi.",
            detail: "Elementary, rational, trig, exponential va special-function natijalari uchun asosiy ilmiy yo'l.",
            bestFor: ["closed-form integrals", "exact reporting", "derivation"],
            parameters: ["assumptions", "simplification level"],
            limitations: ["ba'zi oscillatory yoki non-elementary ifodalar unresolved qaytishi mumkin"],
        },
        {
            id: "risch-heurisch",
            label: "Risch/heurisch route",
            family: "analytic",
            engine: "SymPy",
            status: adapter,
            description: "Elementary closed-form ehtimoli bor integral uchun heurisch/Risch uslubidagi symbolic route.",
            detail: "Code tab va AI explanation uchun method niyati yoziladi; dedicated backend adapter keyingi qadam.",
            bestFor: ["elementary antiderivative search", "rational-log-exp-trig mixes"],
            parameters: ["rewrite strategy", "manual substitution hints"],
            limitations: ["hamma class uchun guarantee bermaydi"],
        },
        {
            id: "numeric-check",
            label: "Exact value numeric check",
            family: "numeric",
            engine: "SymPy",
            status: active,
            description: "Topilgan exact definite qiymatni decimal ko'rinishda tekshiradi.",
            detail: "Bu independent quadrature emas: symbolic definite value ustida sympy.N ishlaydi.",
            bestFor: ["exact result verification", "report decimal value"],
            parameters: ["digits"],
            limitations: ["unresolved integralni mustaqil hisoblamaydi"],
        },
        {
            id: "adaptive-quadrature",
            label: "Adaptive quadrature",
            family: "numeric",
            engine: "SciPy/mpmath",
            status: adapter,
            description: "Smooth definite integrallar uchun error-controlled adaptive subdivision.",
            detail: "Researcher workflow uchun method tanlovi va code draft tayyor; dedicated numeric endpoint ulanadi.",
            bestFor: ["smooth finite intervals", "high accuracy numeric value"],
            parameters: ["absolute tolerance", "relative tolerance", "max subdivisions"],
            limitations: ["singularity va discontinuity alohida split talab qiladi"],
        },
        {
            id: "gauss-legendre",
            label: "Gauss-Legendre quadrature",
            family: "numeric",
            engine: "NumPy/SciPy",
            status: adapter,
            description: "Silliq finite intervalda yuqori tartibli deterministic quadrature.",
            detail: "Node count oshishi bilan aniqlik oshadi, lekin endpoint singularity uchun mos emas.",
            bestFor: ["polynomial-like smooth functions", "fixed-order benchmarks"],
            parameters: ["order", "interval transform"],
            limitations: ["singular/improper integralda yomonlashadi"],
        },
        {
            id: "composite-simpson",
            label: "Composite Simpson",
            family: "numeric",
            engine: "SciPy",
            status: adapter,
            description: "Uniform grid asosida integralni tez baholash va convergence sensitivity ko'rish.",
            detail: "Vizual sample/grid tizimi bilan yaxshi bog'lanadi.",
            bestFor: ["sampled data", "education + diagnostics", "sensitivity sweep"],
            parameters: ["even segment count", "grid resolution"],
            limitations: ["oscillatory va singular holatda ko'p segment talab qiladi"],
        },
        {
            id: "tanh-sinh",
            label: "Tanh-sinh quadrature",
            family: "numeric",
            engine: "mpmath",
            status: adapter,
            description: "Endpoint singularity yoki yuqori aniqlik kerak bo'lganda double-exponential quadrature.",
            detail: "Improper/endpoint-risk integrallar uchun researcher-grade numeric fallback sifatida kerak.",
            bestFor: ["endpoint singularity", "high precision", "improper-like transforms"],
            parameters: ["decimal precision", "max degree"],
            limitations: ["juda oscillatory integralda maxsus metod kerak bo'lishi mumkin"],
        },
        {
            id: "monte-carlo",
            label: "Monte Carlo integration",
            family: "numeric",
            engine: "NumPy",
            status: planned,
            description: "High-dimensional yoki domain murakkab bo'lganda sampling asosida baholash.",
            detail: "Single integral uchun oxirgi chora; double/triple va constrained domainlarda foydaliroq.",
            bestFor: ["high dimension", "complex domains", "uncertainty estimates"],
            parameters: ["sample count", "seed", "confidence interval"],
            limitations: ["convergence sekin, deterministic exactness yo'q"],
        },
        {
            id: "residue-contour",
            label: "Residue/contour method",
            family: "analytic",
            engine: "SymPy/manual",
            status: planned,
            description: "Complex-plane integral va contour candidate holatlarda residue theorem bilan yechish.",
            detail: "Complex analysis bo'limi uchun ajratilgan professional method slot.",
            bestFor: ["poles", "closed contours", "Fourier-type integrals"],
            parameters: ["contour", "pole order", "orientation"],
            limitations: ["manual contour assumptions talab qiladi"],
        },
    ],
    differential: [
        {
            id: "auto",
            label: "Auto differential route",
            family: "hybrid",
            engine: "SymPy",
            status: active,
            description: "Derivative, gradient, Hessian yoki ODE signaliga qarab mavjud symbolic route tanlaydi.",
            detail: "Code tab method ni reproducible scriptga yozadi; numeric adapters bosqichma-bosqich ulanadi.",
            bestFor: ["unknown differential task", "symbolic-first workflow"],
            parameters: ["order", "variable", "evaluation point"],
        },
        {
            id: "symbolic-derivative",
            label: "Symbolic derivative/Jacobian",
            family: "analytic",
            engine: "SymPy",
            status: active,
            description: "diff, gradient, Jacobian va Hessian uchun exact symbolic natija.",
            detail: "Research report uchun eng ishonchli va izohlanadigan yo'l.",
            bestFor: ["exact derivatives", "optimization prep", "sensitivity formulas"],
            parameters: ["variables", "order", "simplification"],
        },
        {
            id: "finite-difference",
            label: "Finite difference",
            family: "numeric",
            engine: "NumPy",
            status: adapter,
            description: "Nuqta atrofida central/forward/backward difference bilan sonli hosila.",
            detail: "Black-box function yoki symbolic diff qimmat bo'lganda kerak.",
            bestFor: ["black-box functions", "point derivatives", "validation"],
            parameters: ["step size", "scheme", "error estimate"],
            limitations: ["roundoff va truncation balance talab qiladi"],
        },
        {
            id: "runge-kutta",
            label: "Runge-Kutta IVP",
            family: "numeric",
            engine: "SciPy",
            status: adapter,
            description: "ODE initial value problem uchun RK45/DOP853/BDF tanlash yo'li.",
            detail: "Stiffness signaliga qarab explicit yoki implicit solver tavsiya qilinadi.",
            bestFor: ["ODE IVP", "time evolution", "stiffness diagnostics"],
            parameters: ["rtol", "atol", "max step", "method"],
            limitations: ["boundary-value problem uchun alohida BVP solver kerak"],
        },
        {
            id: "shooting-bvp",
            label: "Shooting / collocation BVP",
            family: "numeric",
            engine: "SciPy",
            status: planned,
            description: "Boundary value problem uchun shooting yoki collocation strategy.",
            detail: "Labda ODE BVP ko'payganda alohida adapterga ajratiladi.",
            bestFor: ["two-point boundary conditions", "eigenvalue BVP"],
            parameters: ["initial guess", "mesh", "tolerance"],
            limitations: ["initial guess sifati muhim"],
        },
    ],
    matrix: [
        {
            id: "auto",
            label: "Auto linear algebra route",
            family: "hybrid",
            engine: "SymPy/NumPy",
            status: active,
            description: "Matrix hajmi, exact/rational signal va RHS borligiga qarab route tanlaydi.",
            detail: "Small exact matrix symbolic, larger numeric matrix decomposition bilan ishlashi kerak.",
            bestFor: ["mixed exact/numeric matrices", "linear systems"],
            parameters: ["dimension", "condition estimate"],
        },
        {
            id: "symbolic-matrix",
            label: "Exact symbolic matrix",
            family: "analytic",
            engine: "SymPy",
            status: active,
            description: "Rational/exact determinant, inverse, eigen va row-reduction uchun symbolic algebra.",
            detail: "Kichik va o'rta o'lchamdagi exact matrixlar uchun professional yo'l.",
            bestFor: ["rational matrices", "exact determinant", "proof/report"],
            parameters: ["simplification", "domain"],
            limitations: ["katta matrixda expression swell bo'ladi"],
        },
        {
            id: "lu",
            label: "LU decomposition",
            family: "numeric",
            engine: "SciPy",
            status: adapter,
            description: "Linear system, determinant va repeated solves uchun pivoted LU.",
            detail: "Dense numeric matrixlarda asosiy practical method.",
            bestFor: ["Ax=b", "dense systems", "determinant"],
            parameters: ["pivoting", "condition warning"],
            limitations: ["ill-conditioned matrix uchun residual/condition tekshiruvi shart"],
        },
        {
            id: "qr",
            label: "QR least squares",
            family: "numeric",
            engine: "NumPy/SciPy",
            status: adapter,
            description: "Overdetermined system va least-squares fit uchun QR route.",
            detail: "Normal equationsdan barqarorroq.",
            bestFor: ["least squares", "rank diagnostics", "orthogonalization"],
            parameters: ["mode", "rank tolerance"],
            limitations: ["severe rank deficiency uchun SVD kerak"],
        },
        {
            id: "svd",
            label: "SVD / pseudo-inverse",
            family: "numeric",
            engine: "NumPy/SciPy",
            status: adapter,
            description: "Ill-conditioned, rank-deficient va dimensionality reduction masalalari uchun SVD.",
            detail: "Researcher uchun condition number, rank va residual bilan birga chiqishi kerak.",
            bestFor: ["ill-conditioned systems", "PCA", "pseudo-inverse"],
            parameters: ["rank tolerance", "full matrices"],
            limitations: ["large dense matrixda qimmat"],
        },
        {
            id: "sparse-iterative",
            label: "Sparse iterative solvers",
            family: "numeric",
            engine: "SciPy sparse",
            status: planned,
            description: "Large sparse system uchun CG/GMRES/BiCGSTAB route.",
            detail: "Preconditioner va convergence log bilan professional ishlashi kerak.",
            bestFor: ["large sparse Ax=b", "PDE discretization"],
            parameters: ["solver", "preconditioner", "max iterations"],
            limitations: ["matrix structure va preconditioner tanlovi muhim"],
        },
    ],
    probability: [
        {
            id: "auto",
            label: "Auto statistical route",
            family: "hybrid",
            engine: "SymPy/SciPy",
            status: active,
            description: "Distribution formulasi yoki dataset signaliga qarab symbolic/statistical route tanlaydi.",
            detail: "Dataset, distribution va simulation workflowlari alohida adapterlarga bo'linadi.",
            bestFor: ["mixed probability tasks", "quick diagnostics"],
            parameters: ["sample size", "distribution family"],
        },
        {
            id: "symbolic-distribution",
            label: "Symbolic distribution calculus",
            family: "analytic",
            engine: "SymPy",
            status: active,
            description: "PDF/PMF/CDF, expectation va variance formulalarini exact ko'rinishda ishlash.",
            detail: "Theoretical probability va report uchun asosiy method.",
            bestFor: ["known distributions", "exact moments", "CDF transforms"],
            parameters: ["support", "parameters", "assumptions"],
        },
        {
            id: "maximum-likelihood",
            label: "Maximum likelihood",
            family: "numeric",
            engine: "SciPy",
            status: adapter,
            description: "Datasetdan distribution parametrlarini likelihood optimization orqali baholash.",
            detail: "CI, standard error va convergence diagnostics bilan chiqishi kerak.",
            bestFor: ["parameter estimation", "model fitting"],
            parameters: ["initial guess", "bounds", "optimizer"],
            limitations: ["local optimum va identifiability tekshiruvi kerak"],
        },
        {
            id: "monte-carlo",
            label: "Monte Carlo simulation",
            family: "numeric",
            engine: "NumPy",
            status: adapter,
            description: "Expectation, probability va risk metriclarni sampling orqali baholash.",
            detail: "Seed, confidence interval va convergence plot bilan researcherga tushunarli bo'ladi.",
            bestFor: ["complex events", "uncertainty propagation", "risk estimates"],
            parameters: ["sample count", "seed", "confidence level"],
            limitations: ["rare event uchun variance reduction kerak"],
        },
        {
            id: "bayesian-mcmc",
            label: "Bayesian MCMC",
            family: "numeric",
            engine: "PyMC/NumPy",
            status: planned,
            description: "Posterior inference uchun MCMC/NUTS route.",
            detail: "Experiment sifatida keyin ulansa, diagnostics: R-hat, ESS, trace summary majburiy bo'ladi.",
            bestFor: ["posterior inference", "hierarchical models"],
            parameters: ["prior", "chains", "draws", "warmup"],
            limitations: ["model specification va convergence diagnostics shart"],
        },
    ],
    "series-limit": [
        {
            id: "auto",
            label: "Auto asymptotic route",
            family: "hybrid",
            engine: "SymPy",
            status: active,
            description: "Limit, series yoki asymptotic signaliga qarab symbolic route tanlaydi.",
            detail: "Dominant balance va expansion methodlari keyingi adapterlarda ajratiladi.",
            bestFor: ["unknown limit/series task", "symbolic-first workflow"],
            parameters: ["point", "order", "direction"],
        },
        {
            id: "symbolic-limit",
            label: "Symbolic limit",
            family: "analytic",
            engine: "SymPy",
            status: active,
            description: "Direct limit, one-sided limit va infinity limit uchun exact symbolic method.",
            detail: "L'Hopital ishlatishdan oldin symbolic simplification va assumptions muhim.",
            bestFor: ["exact limits", "continuity checks", "singularity behavior"],
            parameters: ["point", "direction", "assumptions"],
        },
        {
            id: "series-expansion",
            label: "Taylor/Laurent expansion",
            family: "analytic",
            engine: "SymPy",
            status: active,
            description: "Lokal behavior, removable singularity va approximation uchun series expansion.",
            detail: "Dominant term orqali limit va asymptotic xulosa olinadi.",
            bestFor: ["local approximation", "singular points", "error terms"],
            parameters: ["order", "center", "branch"],
        },
        {
            id: "asymptotic-dominant-balance",
            label: "Dominant balance",
            family: "analytic",
            engine: "SymPy/manual",
            status: adapter,
            description: "Infinity yoki singular nuqtada leading-order behaviorni ajratish.",
            detail: "Researcher uchun qaysi term dominant ekani ochiq ko'rsatiladi.",
            bestFor: ["asymptotic comparison", "large parameter limits"],
            parameters: ["scale", "dominant variable"],
            limitations: ["manual assumptions kerak bo'lishi mumkin"],
        },
        {
            id: "pade-approximation",
            label: "Pade approximation",
            family: "numeric",
            engine: "SymPy/SciPy",
            status: planned,
            description: "Seriesdan rational approximation olish va convergence radiusdan tashqarida baholash.",
            detail: "Approximation quality residual bilan tekshirilishi kerak.",
            bestFor: ["rational approximation", "near-pole behavior"],
            parameters: ["numerator order", "denominator order"],
            limitations: ["spurious poles chiqishi mumkin"],
        },
    ],
};

export function getLaboratoryMethodOptions(module: LaboratoryMethodModule) {
    return laboratoryMethodRegistry[module] ?? laboratoryMethodRegistry.integral;
}
