import type { ProbabilityPreset } from "./types";

export const PROBABILITY_PRESETS: readonly ProbabilityPreset[] = [
    {
        label: "Time-Series Demand Pulse",
        mode: "time-series",
        dataset: "112, 118, 121, 126, 133, 129, 138, 144, 149, 153, 159, 166",
        parameters: "window=3; horizon=2; period=4",
        dimension: "1d temporal",
        description: "Trend, moving average, forecast va lag-1 signalini bir joyda ko'rsatadigan showcase.",
    },
    {
        label: "Signal Noise Snapshot",
        mode: "descriptive",
        dataset: "12, 15, 13, 17, 19, 18, 14, 16, 20, 22",
        parameters: "bins=6",
        dimension: "1d",
        description: "Descriptive summary, spread audit va histogram ko'rish uchun tez showcase.",
    },
    {
        label: "Normal Tail Audit",
        mode: "distributions",
        dataset: "x=1.96",
        parameters: "family=normal; mu=0; sigma=1",
        dimension: "1d",
        description: "Normal taqsimot, tail probability va confidence intuition uchun.",
    },
    {
        label: "Poisson Queue Pulse",
        mode: "distributions",
        dataset: "x=7",
        parameters: "family=poisson; lambda=5.5",
        dimension: "count process",
        description: "Discrete count probability va queue/event modelling showcase.",
    },
    {
        label: "Bayesian Conversion Audit",
        mode: "bayesian",
        dataset: "successes=58; trials=100",
        parameters: "prior_alpha=2; prior_beta=3; future_n=20; sampler=mh; seed=11",
        dimension: "posterior lane",
        description: "Beta-binomial posterior, credible interval va posterior density uchun.",
    },
    {
        label: "AB Test Inference",
        mode: "inference",
        dataset: "control: 42/210; variant: 57/205",
        parameters: "alpha=0.05",
        dimension: "2-group",
        description: "Hypothesis test, p-value va confidence interval signalini ochadi.",
    },
    {
        label: "One-Way ANOVA Screen",
        mode: "inference",
        dataset: "12, 13, 14, 15 | 10, 11, 12, 11 | 18, 19, 20, 17",
        parameters: "test=anova",
        dimension: "3-group",
        description: "Group variance split va F-statisticni ko'rsatadigan inference showcase.",
    },
    {
        label: "Quadratic Response Fit",
        mode: "regression",
        dataset: "(1,2.4), (2,3.1), (3,4.9), (4,7.8), (5,11.6), (6,16.1)",
        parameters: "model=quadratic",
        dimension: "2d",
        description: "Linear emas, quadratic fit, residual signal va forecast intuition uchun.",
    },
    {
        label: "Multiple Regression Lab",
        mode: "regression",
        dataset: "(1.0,0.5|3.2), (1.5,0.8|4.0), (2.0,1.2|5.1), (2.4,1.6|6.0), (2.9,1.8|6.7)",
        parameters: "model=multiple",
        dimension: "2 predictors",
        description: "Multiple regression, coefficient audit va residual risk signalini ochadi.",
    },
    {
        label: "Correlation Matrix Atlas",
        mode: "multivariate",
        dataset: "4.2, 1.1, 8.2; 4.8, 1.4, 8.9; 5.1, 1.7, 9.4; 5.7, 2.0, 10.1; 6.3, 2.3, 10.8",
        parameters: "labels=signal, lag, output",
        dimension: "3-variable",
        description: "Covariance, correlation heatmap va paired scatter ko'rish uchun.",
    },
    {
        label: "Monte Carlo Pi Deck",
        mode: "monte-carlo",
        dataset: "inside-circle estimator",
        parameters: "samples=5000; seed=42",
        dimension: "simulation",
        description: "Monte Carlo estimate, variance signal va convergence intuition uchun.",
    },
    {
        label: "Bootstrap Confidence Sweep",
        mode: "monte-carlo",
        dataset: "11, 13, 15, 14, 16, 18, 17, 19, 21, 20",
        parameters: "method=bootstrap; rounds=400; seed=21",
        dimension: "resampling",
        description: "Bootstrap interval va resampling spread'ni ko'rsatadi.",
    },
    {
        label: "Sampler Comparison Deck",
        mode: "monte-carlo",
        dataset: "inside-circle estimator",
        parameters: "method=sampler_compare; samples=2500; seed=17",
        dimension: "simulation",
        description: "Crude va stratified sampler farqini convergence bilan ko'rsatadi.",
    },
];

export const PROBABILITY_WORKFLOW_TABS = [
    { id: "solve", label: "Solve" },
    { id: "visualize", label: "Visualize" },
    { id: "compare", label: "Compare" },
    { id: "report", label: "Report" },
] as const;
