import type { SeriesLimitPreset } from "./types";

export const SERIES_LIMIT_PRESETS: readonly SeriesLimitPreset[] = [
    {
        label: "Classic Limit Probe",
        mode: "limits",
        expression: "(sin(x))/x",
        auxiliary: "x -> 0",
        dimension: "1 variable",
        description: "Foundational limit, local behavior va candidate result signalini ko'rsatadi.",
    },
    {
        label: "Removable Singularity",
        mode: "limits",
        expression: "(1-cos(x))/x^2",
        auxiliary: "x -> 0",
        dimension: "1 variable",
        description: "Cancellation va local series expansion talab qiladigan removable singularity limiti.",
    },
    {
        label: "Pole Sign Analysis",
        mode: "limits",
        expression: "1/(x-2)",
        auxiliary: "x -> 2",
        dimension: "1 variable",
        description: "Pole-type limit va one-sided sign behavior uchun template.",
    },
    {
        label: "Infinity Dominant Balance",
        mode: "limits",
        expression: "(3*x^2+1)/(x^2-4*x)",
        auxiliary: "x -> inf",
        dimension: "asymptotic",
        description: "Infinity limitlarda dominant-degree balance va asymptotic lane uchun.",
    },
    {
        label: "Oscillatory Infinity",
        mode: "limits",
        expression: "sin(x)",
        auxiliary: "x -> inf",
        dimension: "oscillatory",
        description: "Oscillatory infinite limits va non-stabilizing tail behavior uchun.",
    },
    {
        label: "Sequence Convergence Deck",
        mode: "sequences",
        expression: "(1 + 1/n)^n",
        auxiliary: "n -> inf",
        dimension: "discrete",
        description: "Sequence limit, monotone behavior va asymptotic intuition uchun starter.",
    },
    {
        label: "Alternating Series Audit",
        mode: "series",
        expression: "sum((-1)^(n+1)/n, n=1..inf)",
        auxiliary: "alternating",
        dimension: "infinite series",
        description: "Alternating harmonic family, conditional convergence va partial sums showcase.",
    },
    {
        label: "Alternating Remainder Lab",
        mode: "series",
        expression: "sum((-1)^(n+1)/sqrt(n), n=1..inf)",
        auxiliary: "alternating remainder",
        dimension: "alternating research",
        description: "Leibniz remainder estimate va alternating decay research lane uchun.",
    },
    {
        label: "Ratio Test Screen",
        mode: "convergence",
        expression: "sum(n!/n^n, n=1..inf)",
        auxiliary: "ratio test",
        dimension: "infinite series",
        description: "Convergence tooling, dominant term va test-family selection uchun.",
    },
    {
        label: "P-Series Threshold",
        mode: "convergence",
        expression: "sum(1/n^2, n=1..inf)",
        auxiliary: "comparison test",
        dimension: "infinite series",
        description: "P-series threshold, comparison va asymptotic class uchun aniq reference case.",
    },
    {
        label: "Log-Corrected Borderline",
        mode: "convergence",
        expression: "sum(1/(n*log(n)^2), n=2..inf)",
        auxiliary: "integral test",
        dimension: "infinite series",
        description: "Borderline logarithmic decay, singular start index va integral-test lane uchun.",
    },
    {
        label: "Oscillatory Cancellation",
        mode: "series",
        expression: "sum(sin(n)/n, n=1..inf)",
        auxiliary: "comparison",
        dimension: "oscillatory series",
        description: "Oscillatory cancellation va non-monotone taillar uchun tougher family.",
    },
    {
        label: "Dirichlet Oscillation",
        mode: "convergence",
        expression: "sum(sin(n)/sqrt(n), n=1..inf)",
        auxiliary: "Dirichlet test",
        dimension: "oscillatory-decay",
        description: "Dirichlet cancellation, bounded partial sums va oscillatory tails uchun research template.",
    },
    {
        label: "Abel Boundary Shell",
        mode: "power-series",
        expression: "sum(x^n*sin(n)/n, n=1..inf)",
        auxiliary: "center=0; Abel screen",
        dimension: "power-oscillatory",
        description: "Abel-style boundary approach va oscillatory coefficient families uchun.",
    },
    {
        label: "Cesaro Borderline Mean",
        mode: "series",
        expression: "sum((-1)^n, n=0..inf)",
        auxiliary: "Cesaro",
        dimension: "summability",
        description: "Classical Cesaro summability va mean-stabilization behavior uchun template.",
    },
    {
        label: "Tauberian Log Shell",
        mode: "convergence",
        expression: "sum(1/(n*log(n)), n=2..inf)",
        auxiliary: "Tauberian screen",
        dimension: "borderline singular",
        description: "Tauberian-style borderline family va singular growth diagnostics uchun.",
    },
    {
        label: "Factorial Competition",
        mode: "convergence",
        expression: "sum(factorial(n)/(3^n*n!), n=1..inf)",
        auxiliary: "ratio test",
        dimension: "factorial-exponential",
        description: "Factorial/exponential raqobati bo'lgan oilalar uchun stress preset.",
    },
    {
        label: "Harmonic-Derived Shell",
        mode: "convergence",
        expression: "sum(harmonic(n)/n^2, n=1..inf)",
        auxiliary: "comparison",
        dimension: "harmonic-derived",
        description: "Harmonic-derived coefficients va named-series catalog uchun research template.",
    },
    {
        label: "Power Series Radius",
        mode: "power-series",
        expression: "sum(x^n/n, n=1..inf)",
        auxiliary: "center=0",
        dimension: "power series",
        description: "Radius of convergence va local expansion workflow uchun starter preset.",
    },
    {
        label: "Endpoint Stress Test",
        mode: "power-series",
        expression: "sum(x^n/sqrt(n), n=1..inf)",
        auxiliary: "center=0",
        dimension: "power series",
        description: "Radius ichida va endpointlarda qaysi test ishlashini ko'rsatadigan stricter preset.",
    },
];

export const SERIES_LIMIT_WORKFLOW_TABS = [
    { id: "solve", label: "Solve" },
    { id: "visualize", label: "Visualize" },
    { id: "compare", label: "Compare" },
    { id: "report", label: "Report" },
] as const;
