import type { DifferentialWorkspaceTab } from "./types";

export const exportGuides = {
    copy: {
        badge: "Differential export",
        title: "Hosila natijasini nusxa olish",
        description: "Differential hisoboti markdown bo'lib clipboard'ga ko'chadi.",
        confirmLabel: "Nusxa olish",
        steps: [
            "Analitik hosila va numerik point evaluation bitta hisobotga yig'iladi.",
            "Function, variable va tangent line ifodasi ham birga yoziladi.",
            "Mavjud maqolangning kerakli joyiga paste qilasan.",
        ],
        note: "Maqola ichidagi aynan kerakli bo'limni o'zing tanlamoqchi bo'lsang, shu variant to'g'ri.",
    },
    send: {
        badge: "Writer import",
        title: "Hosila natijasini writer'ga yuborish",
        description: "Differential hisobotini yangi writer draft'iga import qiladi.",
        confirmLabel: "Writer'ni ochish",
        steps: [
            "Differential export local storage'ga yoziladi.",
            "Yangi writer draft ochiladi.",
            "Hisobot draft boshiga qo'shiladi.",
        ],
        note: "Agar mavjud writer ichidagi live block'ga yubormoqchi bo'lsang, pastdagi Live Writer Bridge ishlatiladi.",
    },
} as const;

export const workspaceTabs: Array<{ id: DifferentialWorkspaceTab; label: string; description: string }> = [
    { id: "solve", label: "Solve", description: "Input, action bar, primary result va derivation." },
    { id: "visualize", label: "Visualize", description: "Grafik, slope-field, tangent va sensitivity." },
    { id: "compare", label: "Compare", description: "Diagnostics, numeric vs symbolic compare va scenario compare." },
    { id: "report", label: "Report", description: "Report builder, notes va export flow." },
];

export const DIFFERENTIAL_PRESETS = [
    { label: "Wave Packet Tangent Walkthrough", mode: "derivative", expr: "exp(-0.12*x) * (sin(2.8*x) + 0.35*x^2)", variable: "x", point: "1.4", order: "1" },
    { label: "Quantum Wave Function (1D)", mode: "derivative", expr: "exp(-x^2/2) * (2*x^2 - 1)", variable: "x", point: "0.5", order: "1" },
    { label: "4th-Order Oscillation", mode: "derivative", expr: "sin(x) * exp(-0.1 * x)", variable: "x", point: "1.0", order: "4" },
    { label: "Damped Oscillator f''", mode: "derivative", expr: "exp(-0.2*t) * cos(3*t + pi/4)", variable: "t", point: "2", order: "2" },
    { label: "Thermodynamics Potential Grad f", mode: "partial", expr: "exp(-x^2 - y^2) * sin(x*y)", variable: "x, y", point: "1, 0.5", order: "1" },
    { label: "Fluid Velocity Gradient", mode: "partial", expr: "x^2*y - y^3*x + sin(x*y)", variable: "x, y", point: "0.5, 0.5", order: "1" },
    { label: "2D Directional Drift", mode: "directional", expr: "x^2 + x*y + sin(y)", variable: "x, y", point: "1, 0.5", direction: "1, 1", order: "1" },
    { label: "3D Gaussian D_u f", mode: "directional", expr: "exp(-x^2 - y^2 - z^2)", variable: "x, y, z", point: "0.5, 0.5, 0.5", direction: "1, 0, 1", order: "1" },
    { label: "Spherical to Cartesian J", mode: "jacobian", expr: "[r * sin(theta) * cos(phi), r * sin(theta) * sin(phi), r * cos(theta)]", variable: "r, theta, phi", point: "1, 1.57, 0", order: "1" },
    { label: "2-Link Robot Jacobian", mode: "jacobian", expr: "[cos(q1) + 2*cos(q1+q2), sin(q1) + 2*sin(q1+q2)]", variable: "q1, q2", point: "0.5, 1", order: "1" },
    { label: "Rosenbrock Hessian", mode: "hessian", expr: "(1 - x)^2 + 100 * (y - x^2)^2", variable: "x, y", point: "1, 1", order: "1" },
    { label: "Saddle Point Test", mode: "hessian", expr: "x^2 - y^2", variable: "x, y", point: "0, 0", order: "1" },
    { label: "Gravitational Potential H", mode: "hessian", expr: "-1 / sqrt(x^2 + y^2 + z^2)", variable: "x, y, z", point: "1, 1, 1", order: "1" },
    { label: "Exponential ODE IVP", mode: "ode", expr: "y' = y; y(0)=1", variable: "x", point: "y(0)=1", order: "1" },
    { label: "Transport PDE Probe", mode: "pde", expr: "u_t = u_x", variable: "x, t", point: "", order: "1" },
    { label: "Geometric Brownian SDE", mode: "sde", expr: "dX = 0.4*X*dt + 0.2*X*dW; X(0)=1; t:[0,1]; n=240", variable: "t", point: "X(0)=1; t:[0,1]; n=240", order: "1" },
] as const;

export const DIFFERENTIAL_WORKFLOW_TEMPLATES = [
    {
        id: "wave_packet_tangent",
        label: "Wave Packet Tangent",
        description: "Damped wave packet uchun tangent line va slope auditni ko'rsatadi.",
        mode: "derivative",
        expr: "exp(-0.12*x) * (sin(2.8*x) + 0.35*x^2)",
        variable: "x",
        point: "1.4",
        order: "1",
    },
    {
        id: "thermal_gradient_map",
        label: "Thermal Gradient Map",
        description: "2D scalar field, gradient vektori va field mapni birga ochadi.",
        mode: "partial",
        expr: "exp(-0.4*(x^2 + y^2)) * (sin(2*x) + cos(1.5*y))",
        variable: "x, y",
        point: "0.8, -0.6",
        order: "1",
    },
    {
        id: "directional_flow_probe",
        label: "Directional Flow Probe",
        description: "Directional derivative uchun gradient va unit direction overlay beradi.",
        mode: "directional",
        expr: "x^2 - x*y + 2*sin(y)",
        variable: "x, y",
        point: "1.1, 0.7",
        direction: "1, -1",
        order: "1",
    },
    {
        id: "gradient_ascent",
        label: "Gradient Ascent Step",
        description: "Gradient direction for optimization. Start at a point and find steepest ascent direction.",
        mode: "partial",
        expr: "x^2 + y^2",
        variable: "x, y",
        point: "3, 4",
    },
    {
        id: "critical_point_hessian",
        label: "Critical Point Analysis",
        description: "Second-order test: evaluate Hessian at critical point to classify min/max/saddle.",
        mode: "hessian",
        expr: "x^3 - 3*x*y^2",
        variable: "x, y",
        point: "0, 0",
    },
    {
        id: "kinematics_jacobian",
        label: "Kinematics Linearization",
        description: "Jacobian for local linear approximation of a robot arm or coordinate transform.",
        mode: "jacobian",
        expr: "[cos(q1) + cos(q1+q2), sin(q1) + sin(q1+q2)]",
        variable: "q1, q2",
        point: "0.5, 1.0",
    },
    {
        id: "taylor_preview",
        label: "Taylor Series Preview",
        description: "Compute up to 4th-order derivatives for Taylor polynomial approximation.",
        mode: "derivative",
        expr: "sin(x)",
        variable: "x",
        point: "0",
        order: "4",
    },
    {
        id: "directional_sensitivity",
        label: "Directional Sensitivity",
        description: "How fast does f change in direction u? D_u f is the gradient projected onto the unit direction.",
        mode: "directional",
        expr: "x^2 + y^2 + x*y",
        variable: "x, y",
        point: "1, 2",
    },
    {
        id: "ode_ivp_lane",
        label: "ODE IVP Lane",
        description: "First-order ODE with initial condition solved symbolically.",
        mode: "ode",
        expr: "y' = x + y; y(0)=1",
        variable: "x",
        point: "y(0)=1",
    },
    {
        id: "pde_transport_lane",
        label: "PDE Transport Lane",
        description: "Simple first-order PDE routed into pdsolve lane.",
        mode: "pde",
        expr: "u_t = u_x",
        variable: "x, t",
        point: "",
    },
    {
        id: "sde_em_lane",
        label: "SDE Euler-Maruyama",
        description: "Geometric-style stochastic lane with reproducible sample-path simulation.",
        mode: "sde",
        expr: "dX = 0.4*X*dt + 0.2*X*dW; X(0)=1; t:[0,1]; n=240",
        variable: "t",
        point: "X(0)=1; t:[0,1]; n=240",
    },
] as const;
